### ISSUE TITLE
AsyncEnumerable.ToListAsync extension method is not retaining the execution context of async streams

### ISSUE THREAD

**Issue by CXuesong** [dotnet/reactive#1483]
Hello and thank you for using dotnet/reactive. Please select a category and detail your issue by answering the questions there:

#### Bug

Despite our best efforts, bugs can slip into releases or corner cases forgotten about. We will try our best to remedy the situation
and/or provide workarounds. Note that certain (odd) behaviors are by design and as such are not considered bugs.

> Which subcomponent library (Ix, Async.Ix)?

System.Linq.Async
> Which library version?

5.0.0
> What are the platform(s), environment(s) and related component version(s)?

.NET Core 3.1 / .NET 5.0
> What is the use case or problem?

I'm using [MEL scoped logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0#log-scopes) in [async stream](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#asynchronous-streams) function.

I'm calling `ILogger.BeginScope` in my [async stream](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#asynchronous-streams) function. (See [CXuesong/WikiClientLibrary RequestHelper.cs](https://github.com/CXuesong/WikiClientLibrary/blob/e76f8b94ec8528b2be57a12cc1ab4d4a97b3389f/WikiClientLibrary/RequestHelper.cs#L94-L103) for some actual usage.)

I'm consuming my async stream with `ToListAsync` extension method provided by Ix.Async.

I see unexpected `NullReferenceException` when I'm leaving the logging scope in my async stream function.

**Note that MEL logger is using `AsyncLocal` to keep scope information in the synchronization context.**

After checking the following snippets, surprisingly, I found multiple `ConfigureAwait(false)` usages in the `ToListAsync` implementation, and I believe this is the root cause of the Exception.
https://github.com/dotnet/reactive/blob/1e2e5cc463e6fc235381f6eb9aa90aeacdb5748a/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncEnumerablePartition.cs#L330-L341

This is unexpected for me, because in async stream function, I never expect synchronization context get changed, because I've never asked so. See code snippet in the last section for a clear repro.

> What is the expected outcome?

Synchronization context should not get changed inside async stream function.

> What is the actual outcome?

Synchronization context is changed inside async stream function.

> What is the stacktrace of the exception(s) if any?
```
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Extensions.Logging.Console.ConsoleLogScope.DisposableScope.Dispose()
   at WikiClientLibrary.Infrastructures.Logging.WikiLoggingHelper.CombinedDisposable.Dispose() in ~\WikiClientLibrary\WikiClientLibrary\Infrastructures\Logging\WikiLoggingHelper.cs:line 132
   at WikiClientLibrary.RequestHelper.QueryWithContinuation(WikiSite site, IEnumerable`1 parameters, Func`1 beginActionScope, Boolean distinctPages, CancellationToken cancellationToken)+MoveNext() in ~\WikiClientLibrary\WikiClientLibrary\RequestHelper.cs:line 106
   at WikiClientLibrary.RequestHelper.QueryWithContinuation(WikiSite site, IEnumerable`1 parameters, Func`1 beginActionScope, Boolean distinctPages, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource.GetResult()
   at System.Linq.AsyncEnumerable.SelectManyAsyncIterator`2.DisposeAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SelectMany.cs:line 387
   at System.Linq.AsyncEnumerablePartition`1.ToListAsync(CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncEnumerablePartition.cs:line 353
   at ConsoleTestApplication1.Program.HelloWikiGenerators() in ~\WikiClientLibrary\ConsoleTestApplication1\Program.cs:line 131
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ConsoleTestApplication1.Program.Main(String[] args) in ~\WikiClientLibrary\ConsoleTestApplication1\Program.cs:line 28
```

> Do you have a code snippet or project that reproduces the problem?

Let's consider a simplified case instead.

The following [async stream](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#asynchronous-streams) function with `AsyncLocal` usage ([.NET Fiddle](https://dotnetfiddle.net/LGAYRi))
```c#
var stringLocal = new AsyncLocal<string>();

async IAsyncEnumerable<int> IntSequence() {
	stringLocal.Value = "value1";
	await Task.Yield();
	Console.WriteLine("stringLocal.Value: {0}", stringLocal.Value);
	yield return 10;
	Console.WriteLine("stringLocal.Value: {0}", stringLocal.Value);
	yield return 20;
	Console.WriteLine("stringLocal.Value: {0}", stringLocal.Value);
	yield return 30;
	Console.WriteLine("stringLocal.Value: {0}", stringLocal.Value);
}

var list = await IntSequence().ToListAsync();
```
`stringLocal.Value` is expected to keep being "value1" during the whole IntSequence scope. But actually it will become `null` since the first `yield return` statement.

**Comment by CXuesong** [comment]
After some local experiment, the loss of execution context is due to the nature of `yield return` (dotnet/runtime#47802) and removing `ConfigureAwait` after `MoveNextAsync` does not have anything to do with execution context in this case.
