### ISSUE TITLE
CancellationToken in ToAsyncEnumerable can cause NullReferenceException

### ISSUE THREAD

**Issue by slavashar** [dotnet/reactive#1726]
#### Bug

It look like there is a race condition in `ToAsyncEnumerable` which can cause `NullReferenceException` when the cancellation token is requested.

> Which subcomponent library (Ix, Async.Ix)?

Ix

> Which library version?

System.Linq.Async 6.0.1

> What are the platform(s), environment(s) and related component version(s)?

Windows, .NET6

> What is the use case or problem?

Cancellation of `ObservableAsyncEnumerable`.

> What is the expected outcome?

`OperationCanceledException` is thrown.

> What is the actual outcome?

`NullReferenceException` is thrown intermittently.

> What is the stacktrace of the exception(s) if any?

```
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.AsyncEnumerable.ObservableAsyncEnumerable`1.MoveNextCore() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToAsyncEnumerable.Observable.cs:line 88
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 70
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 75
   at Program.<<Main>$>g__ConsumeAsync|0_2(Subject`1 subject, CancellationToken ct) in C:\Users\shara\source\repos\ToAsyncEnumerableTest\Program.cs:line 30
```

> Do you have a code snippet or project that reproduces the problem?

```
using System.Reactive.Subjects;

Parallel.For(1, 10, _ => RunAsync().Wait());

async Task RunAsync()
{
    // Set custom context to avoid sychronous execution of enumerable continuation
    SynchronizationContext.SetSynchronizationContext(new CustomSynchronizationContext());

    using var subject = new Subject<int>();
    using var cts = new CancellationTokenSource();

    var task = ConsumeAsync(subject, cts.Token);

    subject.OnNext(1);
    cts.Cancel();

    try
    {
        await task;
    }
    catch (OperationCanceledException)
    {
        // ignore
    }
}

async Task ConsumeAsync(Subject<int> subject, CancellationToken ct)
{
    await foreach (var _ in subject.ToAsyncEnumerable().WithCancellation(ct))
    {
    }
}

internal class CustomSynchronizationContext : SynchronizationContext
{
}
```

**Comment by theodorzoulias** [comment]
I can reproduce it. [This](https://github.com/dotnet/reactive/blob/6ff36f502d9239c72d7f3524752560b151cd7616/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToAsyncEnumerable.Observable.cs#L88) is the line where the NRE is thrown:

```C#
if (_values!.TryDequeue(out _current!))
```

**Comment by omaskery** [comment]
Hi, is there any known workaround for this, or plans to merge the linked PR in the near future? This is currently affecting me with .NET 7, System.Interactive 6.0.1.

**Comment by kmcclellan** [comment]
Still reproduces on `System.Linq.Async` 7.0.1 (.NET 10, Windows). The two relevant lines are unchanged on `main` as of today: `Dispose()` sets `_values = null`, and `MoveNextCore` does `_values!.TryDequeue(out _current!)` with no null check.

Since #1855 is blocked on "there are no tests around this bug," I had Claude write one that fails 100% of the time:

A test in the style of the existing ones, using the `MyObservable<T>` / `MyDisposable` helpers already in `System.Linq.Async.Tests/System/Linq/Operators/ToAsyncEnumerable.cs`:

```csharp
[Fact]
public async Task ToAsyncEnumerable_Observable_Cancel_DuringSubscribe()
{
    using var c = new CancellationTokenSource();

    var xs = new MyObservable<int>(obs =>
    {
        // Cancellation is requested before MoveNextCore registers OnCanceled, so the
        // registration invokes it synchronously on the consumer's thread.
        c.Cancel();
        return new MyDisposable(() => { });
    }).ToAsyncEnumerable();

    await using var e = xs.GetAsyncEnumerator(c.Token);

    await Assert.ThrowsAnyAsync<OperationCanceledException>(async () => await e.MoveNextAsync());
}
```

**On the design question in #1855.** The repro above deliberately emits nothing before cancelling, so it stays valid regardless of how the "should a buffered item still be produced before halting" question is resolved. It isolates the null-dereference alone.

**Possibly relevant to the "partial vs. full disposal" question:** `Dispose()` also clears `_error`. An `OnError` arriving concurrently with cancellation can be discarded before any consumer observes it, so a genuine failure gets reported as a plain cancellation. Same root cause — `Dispose()` mutates state that `MoveNextCore` reads unsynchronized — which is some evidence for @slavashar's position that the cancellation path shouldn't be calling `Dispose()` at all.

For anyone validating a fix statistically rather than deterministically: driving the cancel from a `Task.Run` inside `Subscribe` (closer to how this shows up in the wild) reproduced at roughly 0.3% — 63 NREs in 20,000 iterations on 7.0.1. We hit this originally as an intermittent CI failure in a GraphQL subscription retry loop, where it surfaced as an unhandled `NullReferenceException` escaping a `catch (OperationCanceledException)` during shutdown.
