### ISSUE TITLE
An Observable.FromEvent observable throws ArgumentException upon subscription

### ISSUE THREAD

**Issue by noseratio** [dotnet/reactive#1771]
#### Bug

An `Observable.FromEvent<EventHandler, EventArgs>` observable throws `ArgumentException` *"Cannot bind to the target method because its signature is not compatible with that of the delegate type"* upon subscription.

> Which library version?

5.0.0

> What are the platform(s), environment(s) and related component version(s)?

Windows, .NET 6.0.5

> What is the use case or problem?

Get an observable from an event, convert it to a task and await the task

> What is the expected outcome?

Task completes when the event is triggered

> What is the actual outcome?

ArgumentException: "Cannot bind to the target method because its signature is not compatible with that of the delegate type"

> What is the stacktrace of the exception(s) if any?

```text
System.ArgumentException: Cannot bind to the target method because its signature is not compatible with that of the delegate type.
   at System.Reflection.RuntimeMethodInfo.CreateDelegateInternal(Type delegateType, Object firstArgument, DelegateBindingFlags bindingFlags)
   at System.Reflection.RuntimeMethodInfo.CreateDelegate(Type delegateType, Object target)
   at System.Reactive.ReflectionUtils.CreateDelegate[TDelegate](Object o, MethodInfo method) in /_/Rx.NET/Source/src/System.Reactive/Internal/ReflectionUtils.cs:line 18
   at System.Reactive.Linq.ObservableImpl.FromEvent`2.GetHandler(Action`1 onNext) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/FromEvent.cs:line 181
   at System.Reactive.Linq.ObservableImpl.EventProducer`2.Session.Initialize() in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/FromEvent.cs:line 315
   at System.Reactive.Linq.ObservableImpl.EventProducer`2.Session.Connect(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/FromEvent.cs:line 268
--- End of stack trace from previous location ---
   at Program.<Main>$(String[] args) in C:\FromEvent\Program.cs:line 14

```
> Do you have a code snippet or project that reproduces the problem?

The runnable project can be download from [here](https://drive.google.com/file/d/1553l3thE-7bGY8hEuy5HU3EAlSal2ozo/view). I might be missing something but this seems to be a very trivial use case of `Observable.FromEvent`:

```c#
using System.Reactive.Linq;
using System.Reactive.Threading.Tasks;

try
{
    var testSource = new TestSource();

    var task = Observable.FromEvent<EventHandler, EventArgs>(
        h => testSource.TestEvent += h,
        h => testSource.TestEvent -= h).ToTask();

    ThreadPool.QueueUserWorkItem(_ => testSource.Fire());

    await task;
}
catch (Exception ex)
{
    Console.WriteLine(ex);
    Console.ReadLine();
}

class TestSource
{
    public event EventHandler? TestEvent;

    public void Fire() => TestEvent?.Invoke(this, EventArgs.Empty);
}
```

Thanks for looking into it! 🙏

**Comment by noseratio** [comment]
Having looked at the implementation of  [`FromEvent`](https://github.com/dotnet/reactive/blob/main/Rx.NET/Source/src/System.Reactive/Linq/Observable/FromEvent.cs), I now realize I should be just use be using `FromEventPattern` instead, which deals with delegates taking both `object? sender` and `EventArgs`-derived args. 

This must be a FAQ, but somehow I couldn't really find anything searching for *"Cannot bind to the target method because its signature is not compatible with that of the delegate type" + FromEvent*.

**Comment by noseratio** [comment]
To my future self: not that we should do it, but it's still possible to use the more generic version `FomEvent` (vs `FromEventPattern`), like this:

```c#
var task = Observable.FromEvent<EventHandler, EventArgs>(
    h => (object? sender, EventArgs e) => h(e),
    h => testSource.TestEvent += h,
    h => testSource.TestEvent -= h)
    .FirstAsync()
    .ToTask();
```
