### ISSUE TITLE
System.Linq.AsyncEnumerable.SkipLast() throws an exception

### ISSUE THREAD

**Issue by viceroypenguin** [dotnet/reactive#1783]
#### Bug

Despite our best efforts, bugs can slip into releases or corner cases forgotten about. We will try our best to remedy the situation
and/or provide workarounds. Note that certain (odd) behaviors are by design and as such are not considered bugs.

> Which subcomponent library (Ix, Async.Ix)?
System.Linq.Async

> Which library version?
6.0.1

> What are the platform(s), environment(s) and related component version(s)?
All

> What is the use case or problem?
Calling `.SkipLast()` with a zero or negative number with a non-collection async enumerable will throw an exception.

> What is the expected outcome?
A list of two items (5, 6). Same behavior as `await AsyncEnumerable.Range(5,2).SkipLast(-4).ToListAsync()`

> What is the actual outcome?
An exception: `InvalidOperationException` (Queue empty)`

> What is the stacktrace of the exception(s) if any?
```
  at System.Collections.Generic.Queue`1.ThrowForEmptyQueue()
   at System.Collections.Generic.Queue`1.Dequeue()
   at System.Linq.AsyncEnumerable.<SkipLast>g__Core|343_0[TSource](IAsyncEnumerable`1 source, Int32 count, CancellationToken cancellationToken)+MoveNext() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SkipLast.cs:line 54
   at System.Linq.AsyncEnumerable.<SkipLast>g__Core|343_0[TSource](IAsyncEnumerable`1 source, Int32 count, CancellationToken cancellationToken)+MoveNext() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SkipLast.cs:line 52
   at System.Linq.AsyncEnumerable.<SkipLast>g__Core|343_0[TSource](IAsyncEnumerable`1 source, Int32 count, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
```

> Do you have a code snippet or project that reproduces the problem?
Code to trigger error:
```csharp
var list = await Test().SkipLast(-4).ToListAsync();

async IAsyncEnumerable<int> Test()
{
	yield return 5;
	yield return 6;
}
```

**Comment by theodorzoulias** [comment]
What's even more strange is that passing negative `count` values is allowed. Based on the XML documentation it's not allowed:

https://github.com/dotnet/reactive/blob/85f1eb7c53e27cccdbeee3e0b044916168843fcc/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SkipLast.cs#L22

But the implementation thinks otherwise:

https://github.com/dotnet/reactive/blob/85f1eb7c53e27cccdbeee3e0b044916168843fcc/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SkipLast.cs#L32-L42

That's the definition of half-baked software IMHO.
