### ISSUE TITLE
BUG: RefCount with MinObservers > 1 Behaves Unexpectedly

### ISSUE THREAD

**Issue by mikeronayne** [dotnet/reactive#2173]
### Code

```csharp
Subject<int> subj = new();

var refCount = subj.Publish().RefCount(minObservers: 2);

subj.OnNext(1);

var sub1 = refCount.Subscribe(c => Console.WriteLine($"sub1: {c}"));

subj.OnNext(2);

var sub2 = refCount.Subscribe(c => Console.WriteLine($"sub2: {c}"));

subj.OnNext(3);

sub1.Dispose();

subj.OnNext(4);

var sub3 = refCount.Subscribe(c => Console.WriteLine($"sub3: {c}"));

subj.OnNext(5);

var sub4 = refCount.Subscribe(c => Console.WriteLine($"sub4: {c}"));

subj.OnNext(6);

sub2.Dispose();

sub3.Dispose();

sub4.Dispose();
```

### Expected Output

I would expect not to receive values until `sub2` has subscribed. Then I would expect not to receive values after `sub1` is disposed. Then I would expect to receive values again after `sub3` has subscribed.

```
sub1: 3
sub2: 3
sub2: 5
sub3: 5
sub2: 6
sub3: 6
sub4: 6
```

### Actual Output

1. `sub2` should not have received value 4 since we were below `minObservers` at that point.
2. Definitely shouldn't have gotten an exception on `sub3` subscribing.

```
sub1: 3
sub2: 3
sub2: 4

InvalidOperationException: Disposable has already been assigned.
at System.Reactive.Disposables.SingleAssignmentDisposableValue.set_Disposable(IDisposable value) 
at System.Reactive.Linq.ObservableImpl.RefCount`1.Eager._.Run()   at System.Reactive.Linq.ObservableImpl.RefCount`1.Eager.Run(_ sink) 
at System.Reactive.Producer`2.<>c.<SubscribeRaw>b__1_0(ValueTuple`2 tuple) 
at System.Reactive.Concurrency.Scheduler.<>c__75`1.<ScheduleAction>b__75_0(IScheduler _, ValueTuple`2 tuple)
at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action)
at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action)
at System.Reactive.Concurrency.Scheduler.ScheduleAction[TState](IScheduler scheduler, TState state, Action`1 action)
at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
at System.Reactive.Producer`2.Subscribe(IObserver`1 observer)
at System.ObservableExtensions.Subscribe[T](IObservable`1 source, Action`1 onNext)   at UserQuery.Main(), line 21
```

If this IS expected and not a bug, would love an explanation of what I'm misunderstanding. Thank you!

**Comment by SlyCedix** [comment]
The documentation on RefCount<TSource>(IConnectableObservable<TSource> source, int minObservers) (as well as all RefCount overloads) states that the observable stays connected as long as there is one subscription to the source. This may be an error, but the functionality is consistent with documentation. Given that fact, the expected value would be as follows:

```
sub1: 3
sub2: 3
sub2: 4
sub2: 5
sub3: 5
sub2: 6
sub3: 6
sub4: 6
```

The exception looks like it's due to a bug here:

https://github.com/dotnet/reactive/blob/fefe75993de542bc8dc6e01287fce0956a6770ab/Rx.NET/Source/src/System.Reactive/Linq/Observable/RefCount.cs#L76

The error happens as follows:
```csharp
Subject<int> subj = new();
var refCount = subj.Publish().RefCount(minObservers: 2);

var sub1 = refCount.Subscribe(c => Console.WriteLine($"sub1: {c}")); // count == 1, doConnect = false
var sub2 = refCount.Subscribe(c => Console.WriteLine($"sub2: {c}")); // count == 2, doConnect = true
sub1.Dispose(); // count == 1, no check to disconnect
var sub3 = refCount.Subscribe(c => Console.WriteLine($"sub3: {c}")); // count == 2, doConnect = true, attempts to assign _parent._source.Connect() to an already assigned SingleAssignmentDisposableValue
```

**Comment by idg10** [comment]
As @SlyCedix says, the behaviour of _not_ disconnecting when we drop below the minimum observer number is expected: this is a threshold at which to trigger the connection, and it is 'sticky', in that we then remain connected if the number drops below that, as long as it does not drop to zero.

And also, yes, the exception is definitely a bug!

I've got a fix for this now. It's not released yet, but it's currently available for testing in the `6.0.2-preview.2.g79e191f61d` release on the Rx.NET NuGet package feed.  If you add this in a `NuGet.config` file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="Rx.NET" value="https://pkgs.dev.azure.com/dotnet/Rx.NET/_packaging/RxNet/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

you'll be able to try that preview version out.

(Don't try any of the 7.0.0 previews on that feed. None of those actually feature this bugfix yet!)

**Comment by idg10** [comment]
In investigating this bug I concluded that it slipped through because the existing unit tests for `RefCount` were inadequate. I've added several more, with the result that I've discovered two more `RefCount` bugs:

* #2214
* #2215

Those are related to this bug in that they occur when `minObservers` is greater than 1, but those only affect cases where we specify a `disconnectDelay`.

**Comment by idg10** [comment]
Build `6.0.2-preview.6.g16f94b2f9b` up on the private feed (see above) now fixes those other two bugs too.

I'm planning to do a beta release to the public NuGet feed in the next day or two.

**Comment by idg10** [comment]
Fixed in [6.0.2](https://www.nuget.org/packages/System.Reactive/6.0.2)
