### ISSUE TITLE
Observer auto unsubscribe with Buffer & SelectMany

### ISSUE THREAD

**Issue by CleanCoder** [dotnet/reactive#851]
We have the following customize class to receive events from kafka. (A thread is responsible for polling messages from kafka and call EntityBaseObservable::SendMessage to produce events).
The EntityBaseObservable will be composed with other events via Rx's Merge method. Then we buffer the events for 3 seconds and call SelectMany method to provide events for client to subscribe . The client code subscribe the  event and will never call unsubscribe or dispose method. 
The problem is that the Unsubscriber<T>'s Dispose method has been triggered sometimes (once in a day), and we would like to know why it happened and how could we prevent it. 
Any suggestion are welcome.

```cs
   public class EntityBaseObservable<T> : IObservable<T>, ISendMessage<T> where T : EntityBase
   {
       private readonly List<IObserver<T>> _observers = new List<IObserver<T>>();
       private static readonly Logger Logger = LogManager.GetCurrentClassLogger();

       public IDisposable Subscribe(IObserver<T> observer)
        {
            if (!_observers.Contains(observer))
            {
                Logger.InfoExt($"Subscribe:{observer.ToString()}");
                _observers.Add(observer);
            }

            return new Unsubscriber<T>(_observers, observer);
        }

       public void SendMessage(T obj)
       {
           for (int i = 0; i < _observers.Count; i++)
           {
               var observer = _observers[i];
               observer.OnNext(obj);
           }
       }

       private class Unsubscriber<T> : IDisposable where T : EntityBase
       {
           private readonly List<IObserver<T>> _observers;
           private readonly IObserver<T> _observer;

           public Unsubscriber(List<IObserver<T>> observers, IObserver<T> observer)
           {
               this._observers = observers;
               this._observer = observer;
           }

           public void Dispose()
           {
               if (_observer != null && _observers.Contains(_observer))
               {
                   Logger.FatalExt($"UnsSubscribe: {_observer.ToString()}; StackTrace: {TraceUtil.GetStackTraceInfo()}");
               |
           }
       }
`
 protected IObservable<RoomCountChangeEvent> ConvertBufferedDistinctedObservable(
            IObservable<RoomCountChangeEvent> events)
        {
            return events.Buffer(TimeSpan.FromSeconds(3))
                         .SelectMany(_ => _.Distinct(event => event .GetHashCode()));
        }
```

**StackTrace during Unsubscriber happening:**

```
 at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Sink`1.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Sink`1.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Sink`1.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.CompositeDisposable.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Sink`1.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.CompositeDisposable.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Sink`1.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.CompositeDisposable.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Sink`1.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.CompositeDisposable.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Sink`1.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.CompositeDisposable.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Sink`1.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Sink`1.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Sink`1.Dispose()
   at System.Reactive.Disposables.SingleAssignmentDisposable.Dispose()
   at System.Reactive.Disposables.StableCompositeDisposable.Binary.Dispose()
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.NoSelectorImpl.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Buffer`1.BufferTimeShift.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Merge`1._.Iter.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Merge`1._.Iter.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Merge`1._.Iter.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Merge`1._.Iter.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Merge`1._.Iter.OnError(Exception error)
   **at System.Reactive.Linq.ObservableImpl.SelectMany`2.NoSelectorImpl.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.SelectManyImpl.OnCompletedTask(Task`1 task)**
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by danielcweber** [comment]
Browsing through the stack trace it's apparent that you somewhere pass tasks into `SelectMany`. One of these tasks is in a faulted state, triggering an OnError chain and unsubscription.

**Comment by CleanCoder** [comment]
Thanks  danielcweber, this is really helpful. 
One more question, is it possible to swallow the exception? In our situation, the events is more like a stream, we don't want to break or stop the whole pipeline because of one event failed.  Add try-catch for all logic during composite the pipeline is boring and error-prone (missing some places).

**Comment by bartdesmet** [comment]
This is indeed caused by a faulted task in the `SelectMany` operator. If you only expect tasks to cause failures, you could be explicit about `.ToObservable()` on such tasks and use a custom extension method that converts `Task<T>` into `IObservable<T>` while handling errors in a way other than calling `OnError`.

FWIW, an early design of the `ExceptionServices` facility (see [here](https://github.com/dotnet/reactive/blob/master/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.cs)) prior to shipping v2.0 RTM had a mechanism in it to mediate all exception propagation throughout Rx, but we ultimately decided to drop it because it was a global sledgehammer that would impact each and every use of Rx in the process. The idea was something like this:

* Every `try...catch...` would check with exception services as to whether to handle the exception. Today, we'd use `try...catch...when...` to write this; back then, we didn't have filtered exception handling in C#, so it got tedious to write everywhere.
* Every `observer.OnError(ex)` would be mediated via the exception services as `observer.TryOnError(ex)`, adding additional branching throughout the code to have the caller check what to do next (thus requiring operator code to make decisions whether to skip events or do something else).

The design point for this was to enable hardening of service code in the face of exceptions, e.g. to avoid that a long-running subscription with tons of state would be shut down because of an exception, but do so by having the service opt in to this by installing a different exception service (while the default would always be eager unconditional exception propagation). Ultimately, internal services like Reactor built here in Bing/Azure did away with this by hardening sources against exceptions and by rewriting reactive query expression trees to inject exception handling where needed, rather than doing it using some global configuration.
